import type { CameraAbilityUpgradeTree } from "./types.js";

export const CAMERA_ABILITY_UPGRADE_TREES: CameraAbilityUpgradeTree[] = [
  {
    abilityId: "screen_shake",
    displayName: "Screen Shake",
    levels: [
      {
        level: 1,
        name: "Basic Shake",
        description: "Shake opponent camera with low intensity.",
        unlockRequirement: { type: "default" },
        stats: {
          intensity: 0.3,
          durationMs: 2000,
          chaosPointsCost: 20,
          cooldownMs: 30000,
        },
      },
      {
        level: 2,
        name: "Aftershock",
        description: "Adds a delayed aftershock after the initial shake.",
        unlockRequirement: { type: "xp", amount: 100 },
        stats: {
          intensity: 0.5,
          durationMs: 3000,
          chaosPointsCost: 20,
          cooldownMs: 30000,
          features: ["aftershock"],
        },
      },
      {
        level: 3,
        name: "Earthquake",
        description: "Stronger shake with small splash pressure potential.",
        unlockRequirement: { type: "xp", amount: 300 },
        stats: {
          intensity: 0.8,
          durationMs: 4000,
          chaosPointsCost: 25,
          cooldownMs: 40000,
          features: ["splash_targets_2"],
        },
      },
      {
        level: 4,
        name: "Tremor",
        description: "Adds tilt behavior and heavier disorientation.",
        unlockRequirement: {
          type: "achievement",
          achievementId: "shake_master",
          description: "Use Screen Shake 100 times",
        },
        stats: {
          intensity: 1.0,
          durationMs: 5000,
          chaosPointsCost: 30,
          cooldownMs: 45000,
          features: ["tilt_enabled"],
        },
      },
      {
        level: 5,
        name: "Catastrophe",
        description: "Ultimate shake with extra combo effects.",
        unlockRequirement: { type: "currency", amount: 150, currency: "chaos_tokens" },
        stats: {
          intensity: 1.5,
          durationMs: 6000,
          chaosPointsCost: 50,
          cooldownMs: 90000,
          features: ["target_all", "spin_combo", "zoom_combo"],
        },
      },
    ],
  },
  {
    abilityId: "drunk_vision",
    displayName: "Drunk Vision",
    levels: [
      {
        level: 1,
        name: "Tipsy Shot",
        description: "Light drunk mode: mild sway and subtle blur.",
        unlockRequirement: { type: "default" },
        stats: {
          severity: "light",
          durationMs: 8000,
          chaosPointsCost: 25,
          cooldownMs: 45000,
        },
      },
      {
        level: 2,
        name: "Double Shot",
        description: "Medium drunk mode with double-vision pressure.",
        unlockRequirement: { type: "xp", amount: 100 },
        stats: {
          severity: "medium",
          durationMs: 10000,
          chaosPointsCost: 40,
          cooldownMs: 60000,
          features: ["double_vision"],
        },
      },
      {
        level: 3,
        name: "Long Island",
        description: "Longer medium drunk mode with random jolts.",
        unlockRequirement: { type: "xp", amount: 300 },
        stats: {
          severity: "medium",
          durationMs: 15000,
          chaosPointsCost: 60,
          cooldownMs: 75000,
          features: ["random_jolts"],
        },
      },
      {
        level: 4,
        name: "Keg Stand",
        description: "Heavy drunk mode with periodic blackout pulses.",
        unlockRequirement: {
          type: "achievement",
          achievementId: "bartender",
          description: "Successfully drunk-blind 50 players",
        },
        stats: {
          severity: "blackout",
          durationMs: 18000,
          chaosPointsCost: 80,
          cooldownMs: 90000,
          features: ["periodic_blackout"],
        },
      },
      {
        level: 5,
        name: "Alcohol Poisoning",
        description: "Ultimate blackout mode with severe control pressure.",
        unlockRequirement: { type: "currency", amount: 150, currency: "chaos_tokens" },
        stats: {
          severity: "blackout",
          durationMs: 25000,
          chaosPointsCost: 120,
          cooldownMs: 120000,
          features: ["control_block_5s"],
        },
      },
    ],
  },
  {
    abilityId: "camera_spin",
    displayName: "Camera Spin",
    levels: [
      {
        level: 1,
        name: "Dizzy Spell",
        description: "Single rotation with basic disorientation.",
        unlockRequirement: { type: "default" },
        stats: {
          rotations: 1,
          durationMs: 3000,
          chaosPointsCost: 30,
          cooldownMs: 40000,
        },
      },
      {
        level: 2,
        name: "Vertigo",
        description: "Two rotations with nausea filter potential.",
        unlockRequirement: { type: "xp", amount: 100 },
        stats: {
          rotations: 2,
          durationMs: 4000,
          chaosPointsCost: 45,
          cooldownMs: 50000,
          features: ["nausea_filter"],
        },
      },
      {
        level: 3,
        name: "Washing Machine",
        description: "High-rotation spin with alternating direction pressure.",
        unlockRequirement: { type: "xp", amount: 300 },
        stats: {
          rotations: 5,
          durationMs: 6000,
          chaosPointsCost: 65,
          cooldownMs: 60000,
          features: ["alternate_direction"],
        },
      },
      {
        level: 4,
        name: "Blender Mode",
        description: "Heavy spin combined with random zoom swings.",
        unlockRequirement: {
          type: "achievement",
          achievementId: "spin_doctor",
          description: "Make opponents spin 500 full rotations cumulative",
        },
        stats: {
          rotations: 8,
          zoomDistance: -6,
          durationMs: 8000,
          chaosPointsCost: 90,
          cooldownMs: 75000,
          features: ["random_zoom"],
        },
      },
      {
        level: 5,
        name: "Inception",
        description: "Ultimate multi-axis spin profile.",
        unlockRequirement: { type: "currency", amount: 150, currency: "chaos_tokens" },
        stats: {
          rotations: 10,
          durationMs: 10000,
          chaosPointsCost: 150,
          cooldownMs: 120000,
          features: ["three_axis_spin"],
        },
      },
    ],
  },
];
